[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Change egg to have chance to explode when retriggered by Microwave
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.name == 'Egg' then
    self.ability.extra_value = self.ability.extra_value + self.ability.extra
    if next(SMODS.find_card('j_mxms_soil')) then
        self.ability.extra_value = self.ability.extra_value + self.ability.extra * (G.GAME.mxms_soil_mod - 1)
    end
    self:set_cost()
    SMODS.calculate_context({mxms_scaling_card = true})
'''
position = "after"
payload = '''
if next(SMODS.find_card('j_mxms_microwave')) and pseudorandom('eggsplode' .. G.GAME.round_resets.ante, 1, 20) == 1 then
    G.E_MANAGER:add_event(Event({
        func = function()
            play_sound('mxms_eggsplosion')
            ease_dollars(self.sell_cost)
            self:start_dissolve({G.C.ORANGE}, nil, 1.6)

            check_for_unlock({ type = "eggsplosion" })
            return true;
        end
    }))
    return {
        message = localize('k_mxms_exploded_el'),
        colour = G.C.MONEY
    }
end
'''
match_indent = true
times = 1