[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Apply limits from challenge rule
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
{card_limit = self.GAME.starting_params.hand_size, type = 'hand'})
'''
position = "after"
payload = '''
if self.GAME.modifiers.mxms_highlight_limit then
    G.E_MANAGER:add_event(Event({
        func = function()
            SMODS.change_play_limit(self.GAME.modifiers.mxms_highlight_limit - 5)
            SMODS.change_discard_limit(self.GAME.modifiers.mxms_highlight_limit - 5)
            return true;
        end
    }))
end
'''
match_indent = true
times = 1
