[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Apply modifier to pack choice
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "G.GAME.pack_choices = self.ability.choose or self.config.center.config.choose or 1"
position = "after"
payload = '''
G.GAME.pack_choices = math.min(G.GAME.pack_choices + G.GAME.mxms_choose_mod, self.config.center.config.extra)
'''
match_indent = true
times = 1


    # Add modifier to definitions
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = 'vars = { cfg.choose, cfg.extra },'
position = "at"
payload = 'vars = { math.min(cfg.choose + G.GAME.mxms_choose_mod, cfg.extra), cfg.extra },'
match_indent = true
times = 1